# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: false
os: linux
dist: xenial

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  cleanup: true
  edge: true

jobs:
#   allow_failures:
#   - r: oldrel
#   - r: devel
  include:
  - r: release
  - r: devel
#   - r: oldrel
#     env:
#       - FULL=true
