# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

matrix:
  allow_failures:
  - r: oldrel
  include:
  - r: release
  - r: devel
  - r: oldrel
    env:
      - FULL=true
