# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
os: linux
dist: xenial
warnings_are_errors: false

before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

# jobs:
#   include:
#   - r: release
# #    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
#     before_cache: Rscript -e 'remotes::install_github("r-lib/pkddown")'
#     deploy:
#       provider: script
#       script: Rscript -e 'pkgdown::deploy_site_github()'
#       skip_cleanup: true
#   - r: devel

#    - r: oldrel
#      env:
#        - FULL=true
#    allow_failures:
#    - r: oldrel
#    - r: devel
