on:
  push:
    branches: [main, master, devel]
  release:
    types: [published]
  workflow_dispatch:

name: Update website

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: 'release'

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_cran(c("rmarkdown", "devtools", "pkgdown", "ps"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Configure Git
        run: |
           git config --global user.email "actions@github.com"
           git config --global user.name  "GitHub Actions"

      - name: Roxygenize
        # The vignettes will be built in step "Deploy package"
        run: |
          devtools::document(roclets = c('rd', 'collate', 'namespace'))
        shell: Rscript {0}

      - name: Commit documentation updates
        run: |
          git add --all
          git commit -m 'Re-build documentation' || echo "No changes to commit"
          git push origin || echo "No changes to commit (documentation)"

      - name: Install package
        run: R CMD INSTALL .

      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit README (if README was changed)
        run: |
           git commit README.md -m 'Re-build README.Rmd before pkgdown' || echo "No changes to commit (README)"
           git push origin || echo "No changes to commit (README)"

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: gh-pages
          folder: docs
